version: 0.2

env:
  variables:
    S3_BUCKET: "testing-pipeline-45876"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - chmod +x scripts/install.sh scripts/appsec.sh
      - ./scripts/install.sh
  post_build:
    commands:
      - ./scripts/appsec.sh
