services:
  pokebase:
    image: pokebase
    build: .
    container_name: pokebase
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - POKEBASE_DATA_URL=${POKEBASE_DATA_URL:-}
    volumes:
      - pokebase-data:/app/data
      - pokebase-sprites:/app/static/sprites

volumes:
  pokebase-data:
  pokebase-sprites:
